(set-logic NIA)
(synth-fun z ((y Int) (x Int)) Int
  ((Start Int) (StartBool Bool))
  ((Start Int (0 1 y x 
               (+ Start Start)
               (- Start Start)
               (* Start Start)
               (ite StartBool Start Start)))
   (StartBool Bool ((and StartBool StartBool)
                    (or StartBool StartBool)
                    (not StartBool)
                    (< Start Start)
                    (<= Start Start)
                    (= Start Start)
                    (> Start Start)
                    (>= Start Start)))))
(declare-var y Int)
(declare-var x Int)
(constraint (and (> (z y x) (* x y)) (> (z y x) 0)))
(check-synth)