(set-logic NIA)
(synth-fun z ((x Int) (y Int)) Int
  ((Start Int) (StartBool Bool))
  ((Start Int (0 1 x y
               (+ Start Start)
               (- Start Start)
               (* Start Start)
               (div Start Start)
               (ite StartBool Start Start)))
   (StartBool Bool ((and StartBool StartBool)
                    (or StartBool StartBool)
                    (not StartBool)
                    (< Start Start)
                    (<= Start Start)
                    (= Start Start)
                    (> Start Start)
                    (>= Start Start)))))
(declare-var x Int)
(declare-var y Int)
(constraint (> (z x y) (+ x y)))
(check-synth)